package rules;
import com.example.parceldeliveryapplication.model.Parcel;
import com.example.parceldeliveryapplication.enums.ParcelPriority;
import com.example.parceldeliveryapplication.enums.ParcelCostRuleType;
import com.example.parceldeliveryapplication.exceptions.InvalidVoucherException;
import com.example.parceldeliveryapplication.exceptions.InvalidParcelException;
import com.example.parceldeliveryapplication.config.Constants;
global java.lang.Double cost;
global com.example.parceldeliveryapplication.model.Parcel parcel;

rule "FIRST"
when
$parcel : Parcel($parcel.parcelVolume() >Constants.REJECT_PARCEL || $parcel.weight ==0 || $parcel.parcelVolume() ==0)
then
System.out.println("In drools"+ $parcel.parcelVolume());
Double cost=0.0D;
 end

rule "SECOND"
when
$parcel : Parcel($parcel.weight>Constants.HEAVY_FACTOR)
then
System.out.println("In second---");
Double cost =ParcelCostRuleType.HEAVY_PARCEL.calculateCost($parcel);
System.out.println("cost is--"+cost);
 end

 rule "THIRD"
 when
 $parcel : Parcel($parcel.parcelVolume()<=Constants.SMALL_FACTOR)
 then
  Double cost = ParcelCostRuleType.SMALL_PARCEL.calculateCost($parcel);
  end

  rule "FOURTH"
  when
   $parcel : Parcel($parcel.parcelVolume()>Constants.SMALL_FACTOR && $parcel.parcelVolume()<=Constants.MEDIUM_FACTOR)
   then
     Double cost =ParcelCostRuleType.MEDIUM_PARCEL.calculateCost($parcel);
    end

    rule "FIFTH"
    when
    $parcel : Parcel($parcel.parcelVolume()>Constants.MEDIUM_FACTOR)
    then
      Double cost =ParcelCostRuleType.LARGE_PARCEL.calculateCost($parcel);
     end






